In [4]:
import pandas as pd

orders = pd.read_csv('data/orders.csv', sep=';')
products = pd.read_csv('data/products.csv', sep=';')

In [7]:
orders.head()

,Дата создания,Order ID,ID Покупателя,Статус,Оплачен,Отменен,Отгружен,ID товара,Количество
0,09.11.2019 21:55:51,9,10,"Принят, ожидается оплата",Нет,Нет,Нет,103,5
1,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,86,100
2,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,104,10
3,09.11.2019 12:50:07,7,8,"Принят, ожидается оплата",Нет,Нет,Нет,104,7
4,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,104,5

In [6]:
products.head()

   Product_ID                      Name  Price CURRENCY
0          47      Шатны Полосатый рейс   2999      RUR
1          51  Платье Аленький цветочек   4999      RUR
2          53    Штаны Цветочная Поляна   4999      RUR
3          71       Платье Ночная Жизнь   7999      RUR
4          74  Платье Ночная Жизнь XXXL   8999      RUR

In [17]:
products.rename(columns={'Product_ID' : 'ID товара'}, inplace=True)
products.head()
orders_products = orders.merge(products, how='left', on='ID товара')
orders_products.head(25)

,Дата создания,Order ID,ID Покупателя,Статус,Оплачен,Отменен,Отгружен,ID товара,Количество,Name,Price,CURRENCY
0,09.11.2019 21:55:51,9,10,"Принят, ожидается оплата",Нет,Нет,Нет,103,5,"Носки Подарочные, муж",199.0,RUR
1,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,86,100,"Носки Простые, муж",45.0,RUR
2,09.11.2019 15:05:57,8,9,"Принят, ожидается оплата",Нет,Нет,Нет,104,10,"Носки Подарочные, жен",249.0,RUR
3,09.11.2019 12:50:07,7,8,"Принят, ожидается оплата",Нет,Нет,Нет,104,7,"Носки Подарочные, жен",249.0,RUR
4,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,104,5,"Носки Подарочные, жен",249.0,RUR
5,09.11.2019 12:00:00,6,1,"Принят, ожидается оплата",Нет,Нет,Нет,103,5,"Носки Подарочные, муж",199.0,RUR
6,08.11.2019 08:36:22,5,5,Отменён,Нет,Да,Нет,124,1,Носки беговые Camino,999.0,RUR
7,08.11.2019 08:36:22,4,9,"Принят, ожидается оплата",Нет,Нет,Да,91,1,"Носки Честные, муж",50.0,RUR
8,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,103,3,"Носки Подарочные, муж",199.0,RUR
9,08.11.2019 08:36:22,3,8,"Оплачен, формируется к отправке",Да,Нет,Нет,104,3,"Носки Подарочные, жен",249.0,RUR
10,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,74,1,Платье Ночная Жизнь XXXL,8999.0,RUR
11,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,53,1,Штаны Цветочная Поляна,4999.0,RUR
12,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,137,1,Гольфы детские Снегурочка,99.0,RUR
13,08.11.2019 08:36:21,2,7,Выполнен,Да,Нет,Да,47,1,Шатны Полосатый рейс,2999.0,RUR
14,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,71,1,Платье Ночная Жизнь,7999.0,RUR
15,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,86,1,"Носки Простые, муж",45.0,RUR
16,08.11.2019 08:36:20,1,5,"Оплачен, формируется к отправке",Да,Нет,Нет,51,1,Платье Аленький цветочек,4999.0,RUR
17,01.01.2001 00:00:00,0,1,"Оплачен, формируется к отправке",Да,Нет,Нет,666,1,NaN,NaN,NaN

In [24]:
orders_products['Итого'] = orders_products[orders_products['Оплачен'] == 'Да']['Price']*orders_products['Количество']
pokup = orders_products.groupby('ID Покупателя')['Итого'].sum()
pokup.head()

ID Покупателя
1        0.0
5    13043.0
7    17096.0
8     1344.0
9        0.0
Name: Итого, dtype: float64